### PR TITLE
Patch Openstack Watcher's workload balancing strategy

### LINKED ISSUE #145: [Bug]: Fix Watcher
#### Description

Patch Openstack Watcher's workload balancing strategy by

- Refactor Watcher's Monasca init func
- Use resource_id to query the instance metrics
- Use dict.get to handle the non-existent resource_id exception

<br/>
<br/>

#### How to verify

1). Create a VM and find its host of COS

2). Make the VM to be 100% CPU usage

3). Wait 3 ~ 5 mins to let COS has enough metric to collect

4). SSH to one of control node, then create an audit template with workload-balance strategy by
```sh
$ openstack optimize audittemplate create test-workload-balancer-template workload_balancing --strategy workload_balance
```

5). Create an audit resource by 
```sh
$ openstack optimize audit create -a test-workload-balancer-template -p threshold=0.025 -p period=10 -p metrics=instance_cpu_usage

+---------------+-----------------------------------------------------------------------------------------+
| Field         | Value                                                                                   |
+---------------+-----------------------------------------------------------------------------------------+
| UUID          | 5c69f54c-59a0-4637-9eb5-e29b01678d55                                                    |
| Name          | workload_balance-2025-12-27T17:16:17.335967                                             |
| Created At    | 2025-12-27T17:16:17.368865+00:00                                                        |
| Updated At    | None                                                                                    |
| Deleted At    | None                                                                                    |
| State         | PENDING                                                                                 |
| Audit Type    | ONESHOT                                                                                 |
| Parameters    | {'threshold': 0.025, 'period': 10, 'metrics': 'instance_cpu_usage', 'granularity': 300} |
| Interval      | None                                                                                    |
| Goal          | workload_balancing                                                                      |
| Strategy      | workload_balance                                                                        |
| Audit Scope   | []                                                                                      |
| Auto Trigger  | False                                                                                   |
| Next Run Time | None                                                                                    |
| Hostname      | None                                                                                    |
| Start Time    | None                                                                                    |
| End Time      | None                                                                                    |
| Force         | False                                                                                   |
+---------------+-----------------------------------------------------------------------------------------+
```

6). Check the `/var/log/watcher/decision-engine.log` to see if it have the message below

... Higher than threshold XXX: True <-- like this

```sh
2025-12-28 01:15:56.445 2261742 INFO watcher.decision_engine.strategy.strategies.workload_balance [req-ed2cbbd4-a60d-400c-8768-08220f8f76d9 - - - - -] Host usage for ebba28b1-00ce-4913-95e1-17e1e7007c84: host_cpu_usage_percent is 0.020854166666666663. Higher than threshold 0.02: True
```

7). Check whether Watcher has recommended the VM migration from the the action plan (make sure the Live_migrations_count is higher then 0%)
```sh
$ openstack optimize actionplan list --audit 5c69f54c-59a0-4637-9eb5-e29b01678d55

+--------------------------------------+--------------------------------------+-------------+------------+-------------------------------+
| UUID                                 | Audit                                | State       | Updated At | Global efficacy               |
+--------------------------------------+--------------------------------------+-------------+------------+-------------------------------+
| 384587ec-2a2b-441e-961d-219c295a86f4 | 5c69f54c-59a0-4637-9eb5-e29b01678d55 | RECOMMENDED | None       | Live_migrations_count: 9.09 % |
|                                      |                                      |             |            |                               |
+--------------------------------------+--------------------------------------+-------------+------------+-------------------------------+
```

8). Remember the VM allocation status before executing the action plan of (7)

<img width="1909" height="710" alt="Image" src="https://github.com/user-attachments/assets/65b5c342-f1b1-4b3c-a831-73b3803ec3ad" />

<br/>
<br/>

9). Start the action plan
```sh
$ openstack optimize actionplan start 384587ec-2a2b-441e-961d-219c295a86f4
+---------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Field               | Value                                                                                                                                                                                                                                                             |
+---------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| UUID                | 384587ec-2a2b-441e-961d-219c295a86f4                                                                                                                                                                                                                              |
| Created At          | 2025-12-27T17:16:21+00:00                                                                                                                                                                                                                                         |
| Updated At          | 2025-12-27T17:35:53+00:00                                                                                                                                                                                                                                         |
| Deleted At          | None                                                                                                                                                                                                                                                              |
| Audit               | 5c69f54c-59a0-4637-9eb5-e29b01678d55                                                                                                                                                                                                                              |
| Strategy            | workload_balance                                                                                                                                                                                                                                                  |
| State               | PENDING                                                                                                                                                                                                                                                           |
| Efficacy indicators | [{'name': 'instance_migrations_count', 'description': 'The number of VM migrations to be performed.', 'unit': None, 'value': 1.0}, {'name': 'instances_count', 'description': 'The total number of audited instances in strategy.', 'unit': None, 'value': 11.0}] |
| Global efficacy     | [{'name': 'live_migrations_count', 'description': 'Ratio of migrated virtual machines to audited virtual machines', 'unit': '%', 'value': 9.090909090909092}]                                                                                                     |
| Hostname            | None                                                                                                                                                                                                                                                              |
+---------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

10). Check the action plan of (9) above. The State should be `SUCCEEDED`

```sh
# openstack optimize actionplan show 384587ec-2a2b-441e-961d-219c295a86f4
+---------------------+-------------------------------------------------------------------+
| Field               | Value                                                             |
+---------------------+-------------------------------------------------------------------+
| UUID                | 384587ec-2a2b-441e-961d-219c295a86f4                              |
| Created At          | 2025-12-27T17:16:21+00:00                                         |
| Updated At          | 2025-12-27T17:36:18+00:00                                         |
| Deleted At          | None                                                              |
| Audit               | 5c69f54c-59a0-4637-9eb5-e29b01678d55                              |
| Strategy            | workload_balance                                                  |
| State               | SUCCEEDED                                                         |
| Efficacy indicators | - Description: The number of VM migrations to be performed.       |
|                     |   Name: instance_migrations_count                                 |
|                     |   Unit: null                                                      |
|                     |   Value: 1.0                                                      |
|                     | - Description: The total number of audited instances in strategy. |
|                     |   Name: instances_count                                           |
|                     |   Unit: null                                                      |
|                     |   Value: 11.0                                                     |
|                     |                                                                   |
| Global efficacy     | Live_migrations_count: 9.09 %                                     |
|                     |                                                                   |
| Hostname            | cc2                                                               |
+---------------------+-------------------------------------------------------------------+
```

11). Check the VM allocation status again after executed the action plan of (7). It should be different between this step and (8)

<img width="1908" height="710" alt="Image" src="https://github.com/user-attachments/assets/982c4a8b-860e-4927-a3ae-777320843362" />


<br/>
<br/>

#### Expected result

```sh
[cc1 ~]# openstack optimize audit create -a at1 -p threshold=0.05 -p period=310 -p metrics=instance_cpu_usage
+---------------+-----------------------------------------------------------------------------------------+
| Field         | Value                                                                                   |
+---------------+-----------------------------------------------------------------------------------------+
| UUID          | a8a55d15-1e9b-4c78-8cce-c51f4f786447                                                    |
| Name          | workload_balance-2025-12-13T18:29:02.291466                                             |
| Created At    | 2025-12-13T18:29:02.324736+00:00                                                        |
| Updated At    | None                                                                                    |
| Deleted At    | None                                                                                    |
| State         | PENDING                                                                                 |
| Audit Type    | ONESHOT                                                                                 |
| Parameters    | {'threshold': 0.05, 'period': 310, 'metrics': 'instance_cpu_usage', 'granularity': 300} |
| Interval      | None                                                                                    |
| Goal          | workload_balancing                                                                      |
| Strategy      | workload_balance                                                                        |
| Audit Scope   | []                                                                                      |
| Auto Trigger  | False                                                                                   |
| Next Run Time | None                                                                                    |
| Hostname      | None                                                                                    |
| Start Time    | None                                                                                    |
| End Time      | None                                                                                    |
| Force         | False                                                                                   |
+---------------+-----------------------------------------------------------------------------------------+

[cc1 ~]# openstack optimize actionplan list --audit a8a55d15-1e9b-4c78-8cce-c51f4f786447
+--------------------------------------+--------------------------------------+-------------+------------+--------------------------------+
| UUID                                 | Audit                                | State       | Updated At | Global efficacy                |
+--------------------------------------+--------------------------------------+-------------+------------+--------------------------------+
| 53533630-7f7e-4800-934d-7e9c18d8fbbc | a8a55d15-1e9b-4c78-8cce-c51f4f786447 | RECOMMENDED | None       | Live_migrations_count: 12.50 % |
|                                      |                                      |             |            |                                |
+--------------------------------------+--------------------------------------+-------------+------------+--------------------------------+

[cc1 ~]# openstack optimize actionplan start 53533630-7f7e-4800-934d-7e9c18d8fbbc
+---------------------+-----------------------------------------------------------------------------+
| Field               | Value                                                                                                                                                                                                                                                            |
+---------------------+-----------------------------------------------------------------------------+
| UUID                | 53533630-7f7e-4800-934d-7e9c18d8fbbc                                                                                                                                                                                                                             |
| Created At          | 2025-12-13T18:29:03+00:00                                                                                                                                                                                                                                        |
| Updated At          | 2025-12-13T18:30:26+00:00                                                                                                                                                                                                                                        |
| Deleted At          | None                                                                                                                                                                                                                                                             |
| Audit               | a8a55d15-1e9b-4c78-8cce-c51f4f786447                                                                                                                                                                                                                             |
| Strategy            | workload_balance                                                                                                                                                                                                                                                 |
| State               | PENDING                                                                                                                                                                                                                                                          |
| Efficacy indicators | [{'name': 'instance_migrations_count', 'description': 'The number of VM migrations to be performed.', 'unit': None, 'value': 1.0}, {'name': 'instances_count', 'description': 'The total number of audited instances in strategy.', 'unit': None, 'value': 8.0}] |
| Global efficacy     | [{'name': 'live_migrations_count', 'description': 'Ratio of migrated virtual machines to audited virtual machines', 'unit': '%', 'value': 12.5}]                                                                                                                 |
| Hostname            | None                                                                                                                                                                                                                                                             |
+---------------------+-----------------------------------------------------------------------------+

[cc1 ~]# openstack optimize actionplan show 53533630-7f7e-4800-934d-7e9c18d8fbbc
+---------------------+-------------------------------------------------------------------+
| Field               | Value                                                             |
+---------------------+-------------------------------------------------------------------+
| UUID                | 53533630-7f7e-4800-934d-7e9c18d8fbbc                              |
| Created At          | 2025-12-13T18:29:03+00:00                                         |
| Updated At          | 2025-12-13T18:30:51+00:00                                         |
| Deleted At          | None                                                              |
| Audit               | a8a55d15-1e9b-4c78-8cce-c51f4f786447                              |
| Strategy            | workload_balance                                                  |
| State               | SUCCEEDED                                                         |
| Efficacy indicators | - Description: The number of VM migrations to be performed.       |
|                     |   Name: instance_migrations_count                                 |
|                     |   Unit: null                                                      |
|                     |   Value: 1.0                                                      |
|                     | - Description: The total number of audited instances in strategy. |
|                     |   Name: instances_count                                           |
|                     |   Unit: null                                                      |
|                     |   Value: 8.0                                                      |
|                     |                                                                   |
| Global efficacy     | Live_migrations_count: 12.50 %                                    |
|                     |                                                                   |
| Hostname            | cc1                                                               |
+---------------------+-------------------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by jdjgya**
#### What type of PR is this?

Fix
Refactor

<br/>

#### What this PR does / why we need it

Patch Openstack Watcher's workload balancing strategy by

- Refactor Watcher's Monasca init func
- Use resource_id to query the instance metrics
- Use dict.get to handle the non-existent resource_id exception

<br/>

#### Which issue(s) this PR fixes

https://github.com/bigstack-oss/cubecos/issues/145

<br/>

#### Test result

```sh
[cc1 ~]# openstack optimize audit create -a at1 -p threshold=0.05 -p period=310 -p metrics=instance_cpu_usage
+---------------+-----------------------------------------------------------------------------------------+
| Field         | Value                                                                                   |
+---------------+-----------------------------------------------------------------------------------------+
| UUID          | a8a55d15-1e9b-4c78-8cce-c51f4f786447                                                    |
| Name          | workload_balance-2025-12-13T18:29:02.291466                                             |
| Created At    | 2025-12-13T18:29:02.324736+00:00                                                        |
| Updated At    | None                                                                                    |
| Deleted At    | None                                                                                    |
| State         | PENDING                                                                                 |
| Audit Type    | ONESHOT                                                                                 |
| Parameters    | {'threshold': 0.05, 'period': 310, 'metrics': 'instance_cpu_usage', 'granularity': 300} |
| Interval      | None                                                                                    |
| Goal          | workload_balancing                                                                      |
| Strategy      | workload_balance                                                                        |
| Audit Scope   | []                                                                                      |
| Auto Trigger  | False                                                                                   |
| Next Run Time | None                                                                                    |
| Hostname      | None                                                                                    |
| Start Time    | None                                                                                    |
| End Time      | None                                                                                    |
| Force         | False                                                                                   |
+---------------+-----------------------------------------------------------------------------------------+

[cc1 ~]# openstack optimize actionplan list --audit a8a55d15-1e9b-4c78-8cce-c51f4f786447
+--------------------------------------+--------------------------------------+-------------+------------+--------------------------------+
| UUID                                 | Audit                                | State       | Updated At | Global efficacy                |
+--------------------------------------+--------------------------------------+-------------+------------+--------------------------------+
| 53533630-7f7e-4800-934d-7e9c18d8fbbc | a8a55d15-1e9b-4c78-8cce-c51f4f786447 | RECOMMENDED | None       | Live_migrations_count: 12.50 % |
|                                      |                                      |             |            |                                |
+--------------------------------------+--------------------------------------+-------------+------------+--------------------------------+

[cc1 ~]# openstack optimize actionplan start 53533630-7f7e-4800-934d-7e9c18d8fbbc
+---------------------+-----------------------------------------------------------------------------+
| Field               | Value                                                                                                                                                                                                                                                            |
+---------------------+-----------------------------------------------------------------------------+
| UUID                | 53533630-7f7e-4800-934d-7e9c18d8fbbc                                                                                                                                                                                                                             |
| Created At          | 2025-12-13T18:29:03+00:00                                                                                                                                                                                                                                        |
| Updated At          | 2025-12-13T18:30:26+00:00                                                                                                                                                                                                                                        |
| Deleted At          | None                                                                                                                                                                                                                                                             |
| Audit               | a8a55d15-1e9b-4c78-8cce-c51f4f786447                                                                                                                                                                                                                             |
| Strategy            | workload_balance                                                                                                                                                                                                                                                 |
| State               | PENDING                                                                                                                                                                                                                                                          |
| Efficacy indicators | [{'name': 'instance_migrations_count', 'description': 'The number of VM migrations to be performed.', 'unit': None, 'value': 1.0}, {'name': 'instances_count', 'description': 'The total number of audited instances in strategy.', 'unit': None, 'value': 8.0}] |
| Global efficacy     | [{'name': 'live_migrations_count', 'description': 'Ratio of migrated virtual machines to audited virtual machines', 'unit': '%', 'value': 12.5}]                                                                                                                 |
| Hostname            | None                                                                                                                                                                                                                                                             |
+---------------------+-----------------------------------------------------------------------------+

[cc1 ~]# openstack optimize actionplan show 53533630-7f7e-4800-934d-7e9c18d8fbbc
+---------------------+-------------------------------------------------------------------+
| Field               | Value                                                             |
+---------------------+-------------------------------------------------------------------+
| UUID                | 53533630-7f7e-4800-934d-7e9c18d8fbbc                              |
| Created At          | 2025-12-13T18:29:03+00:00                                         |
| Updated At          | 2025-12-13T18:30:51+00:00                                         |
| Deleted At          | None                                                              |
| Audit               | a8a55d15-1e9b-4c78-8cce-c51f4f786447                              |
| Strategy            | workload_balance                                                  |
| State               | SUCCEEDED                                                         |
| Efficacy indicators | - Description: The number of VM migrations to be performed.       |
|                     |   Name: instance_migrations_count                                 |
|                     |   Unit: null                                                      |
|                     |   Value: 1.0                                                      |
|                     | - Description: The total number of audited instances in strategy. |
|                     |   Name: instances_count                                           |
|                     |   Unit: null                                                      |
|                     |   Value: 8.0                                                      |
|                     |                                                                   |
| Global efficacy     | Live_migrations_count: 12.50 %                                    |
|                     |                                                                   |
| Hostname            | cc1                                                               |
+---------------------+-------------------------------------------------------------------+
```

### CODE REVIEW

**Comment by Eandalf-Bigstack** [comment]
Please rebase to the latest develop branch.

**Review by leechienpang — APPROVED** [review]

**Comment by leechienpang** [comment]
Plz rebase and push your PR to unblock merging.

File: core/modules/config_watcher.cpp [hunk 1]
```diff
@@ -78,6 +78,7 @@ CONFIG_TUNING_SPEC_STR(CUBESYS_CONTROL_ADDRS);
 CONFIG_TUNING_SPEC_STR(CUBESYS_SEED);
 CONFIG_TUNING_SPEC_BOOL(CUBESYS_SALTKEY);
 CONFIG_TUNING_SPEC_BOOL(CUBESYS_HA);
+CONFIG_TUNING_SPEC_STR(KEYSTONE_ADMIN_CLI_PASS);
```
Comment (Eandalf-Bigstack) [inline core/modules/config_watcher.cpp:82]: After adding this tuning, we would need to parse the tuning via the similar pattern in `config_manila.cpp`.

```cpp
CONFIG_OBSERVES(manila, keystone, ParseKeystone, NotifyKeystone);
```

File: core/watcher/yoga_patch/watcher/decision_engine/strategy/strategies/vm_workload_consolidation.py
Comment (Eandalf-Bigstack) [inline core/watcher/yoga_patch/watcher/decision_engine/strategy/strategies/vm_workload_consolidation.py:1]: There is no difference between this file and the original file. Maybe we do not need this one and also the .orig for it?

**Comment by jdjgya** [comment]
Hi @leechienpang @Eandalf-Bigstack ,

Thanks a lot for reminder 🙏 

The branch is already rebased and adjusted the codes which mentioned by Jim above.

Please check 🙏

**Review by Eandalf-Bigstack — APPROVED** [review]
