### PR TITLE
fix: stopping pacemaker with systemd can take 20 min #155

### LINKED ISSUE #352: [Bug]: Health Details – Storage Details log doesn’t show complete information
## Describe the bug

Health Details – Storage Details log doesn’t show complete information

## Version 

Version 3.1.0 CUBE_3.1.0_20250903-0139_a12320a

## To Reproduce

1. Go to the Health Details page on the CubeCOS Web UI.

2. Click the Storage page.

3. Check whether each detail log shows the complete error message.

## Expected behavior

The error message should clearly describe the problem so the user can understand it

## Screenshots

Ceph
Image
Ceph MON
Image
Ceph MGR
Image
Ceph MDS
Image
Ceph OSD
Image

### LINKED ISSUE #353: [Bug]: Health Details – Cloud Computing Details log doesn’t show complete information
## Describe the bug

Health Details – Cloud Computing Details log doesn’t show complete information

## Version 

Version 3.1.0 CUBE_3.1.0_20250903-0139_a12320a

## To Reproduce

1. Go to the Health Details page on the CubeCOS Web UI.

2. Click the Cloud Computing page.

3. Check whether each detail log shows the complete error message.

## Expected behavior

The error message should clearly describe the problem so the user can understand it

## Screenshots

Network
Image
Image
Image
BlockStor
Image
FileStor
Image
ObjectStor
Image
Orchestration
Image
LBaaS
Image
DNSaaS
Image
K8saaS
Image
Instance HA
Image
Compute
Image
Image
Business Logic
Image
Image

### LINKED ISSUE #354: [Bug]: Health Details – Infrascope Details log doesn’t show complete information
## Describe the bug

Health Details – Infrascope Details log doesn’t show complete information

## Version 

Version 3.1.0 CUBE_3.1.0_20250903-0139_a12320a

## To Reproduce

1. Go to the Health Details page on the CubeCOS Web UI.

2. Click the Infrascope page.

3. Check whether each detail log shows the complete error message.

## Expected behavior

The error message should clearly describe the problem so the user can understand it

## Screenshots
Data Pipe
Image
Image
Notifications
Image
Image
Metrics
Image
Image
Image
Log Analytics
Image
Image
Image
Image
Image

### PR DESCRIPTION
**Pull request by leechienpang**
- fix: enrich some SDK health details #352 #353 #354
- new: SDK cmd that runs in parallel and return non zero in case of failures

#### Which issue(s) this PR fixes

Fixes #

#### Special notes for your reviewer

> Note

#### Additional documentation

```docs

```

### CODE REVIEW

**Comment by Eandalf-Bigstack** [comment]
Related issues:

- #155 
- #208

File: core/sdk_sh/modules/sdk_health.sh [hunk 1]
```diff
@@ -1,4 +1,4 @@
-# CUBE SDK
+%# CUBE SDK
```
Comment (Eandalf-Bigstack) [inline core/sdk_sh/modules/sdk_health.sh]: We are having an extra symbol `%` here.

**Review by Eandalf-Bigstack — APPROVED** [review]
